discord:
  - id: "nuclei"
    discord_channel: "continuous-subdomain-monitor"
    discord_username: "Monitor Bot"
    discord_format: "{{data}}"
    discord_webhook_url: "https://discordapp.com/api/webhooks/1067332803840188468/rNtHcz9LNx7LyIPmsWKQTch_Ze_y0VgNRIjLubYWkL3KpSlrsWo72F7-kkM4JFAxBPnA"

# notify -provider-config notify.yaml -data custom text 
