name: GitHub Actions
on:
  push:
    branches:    
      - 'work-flow'

permissions: write-all 
jobs:
  autoamate-with-actions:
    runs-on: ubuntu-latest
    defaults: 
      run:
        shell: bash
    steps:
     - uses: actions/checkout@v2
       with: 
          repository: DK9510/subdomain-monitoring
     - run: |
        echo "hello DK"
        ##this script is for installation of tools in the github vm where workflow runs
        #echo "Running installation script in the github vm
        wget https://go.dev/dl/go1.17.5.linux-amd64.tar.gz 
        sudo tar -xvf go1.17.5.linux-amd64.tar.gz 
        sudo mv -f go /usr/local/
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
        bash scripts/install.sh 
        bash scripts/submonitor.sh
